In [3]:
import numpy as np
import pandas as pd

# Read the CSV file into a DataFrame
wine = pd.read_csv('WineQT.csv', sep=',')

# Display the first 5 rows of the DataFrame
wine.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,1
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,2
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,3
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,4

In [4]:
from sklearn.preprocessing import MinMaxScaler

# Step 1: Convert the quality attribute
wine['quality'] = wine['quality'].apply(lambda x: 0 if x <= 6 else 1)

# Step 2: Normalize all other attributes using min-max scaling
scaler = MinMaxScaler()

# Exclude 'Id' and 'quality' from normalization
attributes = wine.columns.difference(['Id', 'quality'])

wine[attributes] = scaler.fit_transform(wine[attributes])

# Display the transformed dataset
wine.head(20)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,0.247788,0.397260,0.00,0.068493,0.106845,0.149254,0.098940,0.567548,0.606299,0.137725,0.153846,0,0
1,0.283186,0.520548,0.00,0.116438,0.143573,0.358209,0.215548,0.494126,0.362205,0.209581,0.215385,0,1
2,0.283186,0.438356,0.04,0.095890,0.133556,0.208955,0.169611,0.508811,0.409449,0.191617,0.215385,0,2
3,0.584071,0.109589,0.56,0.068493,0.105175,0.238806,0.190813,0.582232,0.330709,0.149701,0.215385,0,3
4,0.247788,0.397260,0.00,0.068493,0.106845,0.149254,0.098940,0.567548,0.606299,0.137725,0.153846,0,4
5,0.247788,0.369863,0.00,0.061644,0.105175,0.179104,0.120141,0.567548,0.606299,0.137725,0.153846,0,5
6,0.292035,0.328767,0.06,0.047945,0.095159,0.208955,0.187279,0.464758,0.440945,0.077844,0.153846,0,6
7,0.238938,0.363014,0.00,0.020548,0.088481,0.208955,0.053004,0.332599,0.511811,0.083832,0.246154,1,7
8,0.283186,0.315068,0.02,0.075342,0.101836,0.119403,0.042403,0.494126,0.488189,0.143713,0.169231,1,8
9,0.185841,0.315068,0.08,0.061644,0.141903,0.208955,0.208481,0.428047,0.425197,0.125749,0.123077,0,10
10,0.088496,0.339041,0.00,0.047945,0.128548,0.223881,0.187279,0.310573,0.661417,0.113772,0.230769,0,12
11,0.283186,0.335616,0.29,0.047945,0.170284,0.119403,0.081272,0.538179,0.409449,0.736527,0.107692,0,13
12,0.345133,0.109589,0.56,0.061644,0.133556,0.507463,0.342756,0.501468,0.440945,0.251497,0.323077,1,16
13,0.292035,0.136986,0.51,0.061644,0.549249,0.238806,0.176678,0.501468,0.236220,0.449102,0.123077,0,19
14,0.265487,0.184932,0.31,0.095890,0.116861,0.328358,0.229682,0.596916,0.614173,0.191617,0.200000,0,21
15,0.292035,0.212329,0.21,0.047945,0.156928,0.134328,0.109541,0.479442,0.338583,0.347305,0.169231,0,22
16,0.345133,0.253425,0.11,0.095890,0.120200,0.119403,0.215548,0.494126,0.338583,0.119760,0.153846,0,23
17,0.203540,0.191781,0.14,0.102740,0.121870,0.298507,0.120141,0.494126,0.543307,0.179641,0.200000,0,24
18,0.150442,0.184932,0.16,0.034247,0.113523,0.149254,0.060071,0.398678,0.472441,0.137725,0.138462,0,25
19,0.265487,0.198630,0.24,0.061644,0.113523,0.044776,0.017668,0.450073,0.425197,0.155689,0.169231,0,26